[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
django = "~=5.1.12"
gunicorn = "~=23.0.0"
requests = "~=2.32.4"
django-weasyprint = "~=2.4.0"
psycopg = "~=3.2.1"
dj-database-url = "~=2.3.0"
whitenoise = "~=6.9.0"
sentry-sdk = "~=2.25.1"
django-vite = "~=3.1.0"
django-anymail = "~=13.0"
python-dateutil = "~=2.9.0"
django-hosts = "~=6.0"
# note on django-csp: using v4, v3 conf will soon be incompatible
django-csp= "~=4.0"
sib-api-v3-sdk = "~=7.6.0"
openpyxl = "~=3.1.5"
django-cors-headers = "~=4.7.0"
django-storages = {extras = ["s3"], version = "~=1.14.5"}
filetype = "~=1.2"
# tables de travail analytics / Metabase
aiohttp = "~=3.12.15"
responses = "~=0.25.8"
# admin : connexion en tant qu'utilisateur enregistr√©
django-hijack = "~=3.7.4"
geojson = "~=3.2.0"

[dev-packages]
pytest-django = "*"
pytest-mock = "*"
freezegun = "*"
pre-commit = "*"
honcho = "*"
django-debug-toolbar = "*"
exceptiongroup = {version = "~=1.2.2", markers="python_version < '3.13'"}
django-extensions="*"

[requires]
python_version = "3.12"
